---
title: "PADK 02"
author: "Angga Fathan Rofiqy"
date: "`r Sys.Date()`"
output: html_document
---

### Set Working Directory

```{r}
repo  <- gsub  ( "\\\\",  "/",  readClipboard ()  ); repo
```

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/7. Pengantar Analisis Data Kategorik/02")
```

# Data 1

```{r}
library(readxl)
data1 <- read_xlsx("Data1.xlsx")
```

```{r}
library(dplyr)
rank1 <- data1 %>%
  gather(Grup, Nilai) %>%
  arrange(Grup, Nilai)

```

```{r}
library(dplyr)
library(tidyr)

rank1 <- data1 %>%
  pivot_longer(cols = c(Rendah, Tinggi), 
               names_to = "Grup", values_to = "Nilai") %>%
  arrange(Grup, Nilai)

```

# Data 2

```{r}
data2 <- read_xlsx("Data2.xlsx")
```

# Data 3

```{r}
data3 <- read_xlsx("Data3.xlsx")
```

# Data 4

```{r}
data4 <- read_xlsx("Data4.xlsx")
```

# Soal 1

```{r}
soal1 <- read_xlsx("Soal1.xlsx")
```

```{r}

```

# Soal 2

```{r}
soal2 <- read_xlsx("Soal2.xlsx")
```

# Soal 3

```{r}
soal3 <- read_xlsx("Soal3.xlsx")
```

# Soal 4

```{r}
soal4 <- read_xlsx("Soal4.xlsx")
```
